import { useMemo } from "react";
import Aceptarcredito from "components/Modals/Aceptarcredito";
import Denegarcredito from "components/Modals/Denegarcredito";
//import AgregarCliente from "components/Modals/AgregarCliente.js"
export default function useRows() {
  const rows = useMemo(
    () => [
      {
        nombre: "Fernando",
        tidentificacion: "Cedula",
        identificacion: "12535",
        correo: "javier@gmail.com",
        valor: "3.000.000",
        estado:"Rechazado",
        aceptar: <Aceptarcredito />,
        rechazar: <Denegarcredito />,
      },
      {
        nombre: "Fernando",
        tidentificacion: "Cedula",
        identificacion: "12535",
        correo: "javier@gmail.com",
        valor: "3.000.000",
        estado:"Rechazado",
        aceptar: <Aceptarcredito />,
        rechazar: <Denegarcredito />,
      },
      {
        nombre: "Fernando",
        tidentificacion: "Cedula",
        identificacion: "12535",
        correo: "javier@gmail.com",
        valor: "3.000.000",
        estado:"Rechazado",
        aceptar: <Aceptarcredito />,
        rechazar: <Denegarcredito />,
      },
      {
        nombre: "Rodriguez",
        tidentificacion: "Cedula",
        identificacion: "15515",
        correo: "javier@gmail.com",
        valor: "3.000.000",
        estado:"Rechazado",
        aceptar: <Aceptarcredito />,
        rechazar: <Denegarcredito />,
      },
      {
        nombre: "Rodriguez",
        tidentificacion: "Cedula",
        identificacion: "150015",
        correo: "javier@gmail.com",
        valor: "3.000.000",
        estado:"Rechazado",
        aceptar: <Aceptarcredito />,
        rechazar: <Denegarcredito />,
      },
      {
        nombre: "Rodriguez",
        tidentificacion: "Cedula",
        identificacion: "1000283965",
        correo: "javier@gmail.com",
        valor: "3.000.000",
        estado:"Rechazado",
        aceptar: <Aceptarcredito />,
        rechazar: <Denegarcredito />,
      },
      {
        nombre: "Rodriguez",
        tidentificacion: "Cedula",
        identificacion: "1515",
        correo: "javier@gmail.com",
        valor: "3.000.000",
        estado:"Rechazado",
        aceptar: <Aceptarcredito />,
        rechazar: <Denegarcredito />,
      },
      {
        nombre: "Rodriguez",
        tidentificacion: "Cedula",
        identificacion: "1515",
        correo: "javier@gmail.com",
        valor: "3.000.000",
        estado:"Aprobado",
        aceptar: <Aceptarcredito />,
        rechazar: <Denegarcredito />,
      },
      {
        nombre: "Rodriguez",
        tidentificacion: "Cedula",
        identificacion: "1515",
        correo: "javier@gmail.com",
        valor: "3.000.000",
        estado:"Aprobado",
        aceptar: <Aceptarcredito />,
        rechazar: <Denegarcredito />,
      },
      {
        nombre: "Rodriguez",
        tidentificacion: "Cedula",
        identificacion: "1515",
        correo: "javier@gmail.com",
        aceptar: <Aceptarcredito />,
        rechazar: <Denegarcredito />,
      },
      {
        nombre: "Rodriguez",
        tidentificacion: "Cedula",
        identificacion: "1515",
        correo: "javier@gmail.com",
        valor: "3.000.000",
        estado:"Aprobado",
        aceptar: <Aceptarcredito />,
        rechazar: <Denegarcredito />,
      },
      {
        nombre: "Fernando",
        tidentificacion: "Cedula",
        identificacion: "1515",
        correo: "javier@gmail.com",
        valor: "3.000.000",
        estado:"Aprobado",
        aceptar: <Aceptarcredito />,
        rechazar: <Denegarcredito />,
      },
    ],
    []
  );

  return rows;
}
